language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.3
  - 7.4
  - 8.0
  - 8.1
  - hhvm

matrix:
  include:
    - php: 7.3
      dist: precise
    - php: 8.0
      env: SYMFONY_VERSION='^4'
    - php: 8.0
      env: SYMFONY_VERSION='^5'
    # Test against dev dependencies
    - php: 8.1
      env: DEPS=dev

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/lts=$SYMFONY_VERSION; fi;
  - if [ "$DEPS" = 'dev' ]; then composer config minimum-stability dev; fi;

install:
  - composer install --no-progress

script:
  - vendor/bin/phpspec run -f pretty
  - vendor/bin/behat -fprogress --strict
